### ISSUE TITLE
DublinCore tags not output in RSS 2.0 feed

### ISSUE THREAD

**Issue by sherrardb** [shlomif/perl-XML-RSS#19]
@shlomif, i have seen (and understand) your comments that updating `XML::RSS` is not a priority for you, but i was hoping that you might at least be able to shed some light on what i am seeing, and [others](https://perlmonks.org/index.pl?node_id=11146565) have observed as well.

is this behavior (`DublinCore` tags output in 1.0, but not 2.0) intentional (ie, `DublinCore` is not compatible with RSS 2.0 because of the spec), or is it because the code has not been updated to reflect the compatibility, or for some other reason?

i simply want to avoid the situation where i patch things locally, thinking that it is a bug, only to discover that it was a feature, and that my "fix" is producing poorly-formatted RSS.

TIA

**Comment by shlomif** [comment]
hi,

On Fri, 26 May 2023 07:31:46 -0700
sherrardb ***@***.***> wrote:

> @shlomif, i have seen (and understand) your comments that updating `XML::RSS`
> is not a priority for you, but i was hoping that you might at least be able
> to shed some light on what i am seeing, and
> [others](https://perlmonks.org/index.pl?node_id=11146565) have observed as
> well.
> 
> is this behavior (`DublinCore` tags output in 1.0, but not 2.0) intentional
> (ie, `DublinCore` is not compatible with RSS 2.0 because of the spec), or is
> it because the code has not been updated to reflect the compatibility, or for
> some other reason?
> 

sorry, but i haven't studied the RSSes specs too closely. 

> i simply want to avoid the situation where i patch things locally, thinking
> that it is a bug, only to discover that it was a feature, and that my "fix"
> is producing poorly-formatted RSS.
> 

"one doesnt simply..." -
https://knowyourmeme.com/memes/one-does-not-simply-walk-into-mordor ;]

> TIA
> 



-- 

Shlomi Fish       https://www.shlomifish.org/
https://ccmixter.org/files/destinazione_altrove/49997 - “Paint The Sky”

Chuck Norris does not code; when he sits at a computer, it just does whatever
he wants. (By: Kattana.)
    — https://www.shlomifish.org/humour/bits/facts/Chuck-Norris/

Please reply to list if it's a mailing list post - https://shlom.in/reply .

**Comment by sherrardb** [comment]
thanks for the prompt response. i will proceed with caution and will defer to the RSS validator and feedback from the developers of the systems that will ultimately be consuming the feed.
cheers

**Comment by shlomif** [comment]
On Fri, 26 May 2023 21:58:10 -0700
sherrardb ***@***.***> wrote:

> thanks for the prompt response. i will proceed with caution and will defer to
> the RSS validator and feedback from the developers of the systems that will
> ultimately be consuming the feed. cheers
> 

you're welcome, and good luck.

-- 

Shlomi Fish       https://www.shlomifish.org/
https://www.shlomifish.org/humour/ways_to_do_it.html

If a tree falls down in the middle of the forest, and there’s no one there to
hear it… what colour is the tree?
    — Monkey Island 2: LeChuck’s Revenge

Please reply to list if it's a mailing list post - https://shlom.in/reply .
