### ISSUE TITLE
Nested custom link tags break item links

### ISSUE THREAD

**Issue by jkramer** [shlomif/perl-XML-RSS#7]
The parser should only use link tags that are direct children of the item node for the link, not link tags located somewhere deeper in the structure. For example the following XML results in the parsed item's link being `SOME_URLSOME_TEXT` instead of `SOME_URL`:

```xml
<item>
  <link>SOME_URL</link>
  <some_custom_tag>
    <link>SOME_TEXT</link>
  </some_custom_tag>
  ...
</item>
```

Real life example where this bug breaks item URLs: https://aif.ru/rss/all.php

**Comment by shlomif** [comment]
@jkramer : hi! Please put a complete testcase - not just bits and pieces: see http://sscce.org/ and https://github.com/shlomif/how-to-share-code-online . web urls are subject to change and I'm wary of clicking `.ru` URLs.

**Comment by jkramer** [comment]
Hi @shlomif, here's a simple test case:

```perl
#!/usr/bin/env perl

use strict;
use warnings;

use Test::More tests => 2;

use_ok 'XML::RSS';

my $x = XML::RSS->new;

$x->parse(<<EOT);

<rss version="2.0">
  <channel>
    <item>
      <title>random title</title>
      <link>http://correct.url/</link>
      <description>some text</description>

      <random_custom_tag>
        <link>random text that's in a tag named link for whatever reason</link>
      </random_custom_tag>
    </item>
  </channel>
</rss>

EOT

is($x->{items}->[0]->{link}, 'http://correct.url/', 'item link parsed correctly');
```

Output:

```
1..2
ok 1 - use XML::RSS;
not ok 2 - item link parsed correctly
#   Failed test 'item link parsed correctly'
#   at item_link.t line 30.
#          got: 'http://correct.url/random text that's in a tag named link for whatever reason'
#     expected: 'http://correct.url/'
# Looks like you failed 1 test of 2.
```

**Comment by shlomif** [comment]
@jkramer : thanks! I can work with that.

**Comment by shlomif** [comment]
Hi @jkramer ! Sorry, but I let this slip from my mind. Can you try this commit and see if it fixes the issue for you: https://github.com/shlomif/perl-XML-RSS/commit/8b8976d329909e65601630c60bba287c1eedefac . Thanks!

**Comment by shlomif** [comment]
@jkramer: also note that [::LibXML](https://metacpan.org/pod/XML::RSS::LibXML) may work better for you.

**Comment by shlomif** [comment]
@jkramer : ping! Please handle the request.

**Comment by shlomif** [comment]
Should be fixed in v1.62 and closing for now due to @jkramer being non responsive. I can reopen this ticket upon request or one can file new ones.

**Comment by jkramer** [comment]
Hi @shlomif, sorry for the delay. It works alright now, thanks!

**Comment by shlomif** [comment]
On Sat, 02 Jan 2021 06:38:29 -0800
Jonas Kramer <notifications@github.com> wrote:

> Hi @shlomif, sorry for the delay. It works alright now, thanks!
> 

Thanks!

-- 

Shlomi Fish       https://www.shlomifish.org/
Freecell Solver - https://fc-solve.shlomifish.org/

Real men don’t listen to sentences that start with “Real men don’t”.
    — https://whatsup.org.il/article/6023

Please reply to list if it's a mailing list post - https://shlom.in/reply .
