### ISSUE TITLE
Not possible to generate self link in channel

### ISSUE THREAD

**Issue by gdsotirov** [shlomif/perl-XML-RSS#8]
Looking at [module's page](https://metacpan.org/pod/XML::RSS) at CPAN I do not see a way to generate self link to channel, which is reported as "_Missing atom:link with rel=self_" by [W3C's Feed Validation Service](https://validator.w3.org/feed/). The [related doc](https://validator.w3.org/feed/docs/warning/MissingAtomSelfLink.html) explains the meaning of the message. Is it possible to add self link to channel?

**Comment by Lapeth** [comment]
You can add the namespace:
`$rss->add_module(prefix=>'atom', uri=>'http://www.w3.org/2005/Atom');`

And you can add the tag to the channel:
```
$rss->channel(
        ...
        atom        => { link=> 'https://example.com' },
);
<atom:link>https://example.com</atom:link>
```

You can also have a tag with an attribute
```
$rss->channel(
        ...
        atom        => { link=> { 'rel' => 'self' } },
);
<atom:link rel="self"/>
```

It appears, however, that you cannot have a custom tag with both attributes and content; Looking at https://metacpan.org/source/XML::RSS::Private::Output::Base, the `_out_ns_tag` method behaves differently than `_out_tag`, which appears to accept the content by the "content" hash key. `_out_ns_tag` does call `_out_tag`, but only if the value is not a hashref or arrayref, and `_out_tag` only adds attributes if it is a hashref.

Am I missing something here?

**Comment by gdsotirov** [comment]
Thanks for looking into this issue @Lapeth! I was not so obvious for me how to generate the link, but thanks to your input I was able to do so with the following (sample) code:

```perl
  my $rss = XML::RSS->new(version => 2.0, encode_output => 0, encoding => 'utf-8');
  $rss->add_module(prefix=>'atom', uri=>'http://www.w3.org/2005/Atom');

  $rss->channel(title           => "Example feed",
 ...
                atom            => {
                  link  => {
                    'href'      => 'https://example.com/feed',
                    'rel'       => 'self',
                    'type'      => 'application/rss+xml'
                  }
                }
...
  );
```

Which gives me exactly the needed result:

```xml
<atom:link href="https://example.com/feed" rel="self" type="application/rss+xml"/>
```

Thanks again for the help. I thus close the issue.
